// Build the mirage nav grid from the REAL .nav walkable mesh (not the radar PNG): blocked = a cell
// whose centre isn't inside any nav area. Precise (no dilation) so thin walls — like the apartments
// wood door — stay solid and block movement + line-of-sight. Writes src/navGrids.ts in the same
// base64 bit-packed format the app loads, and a verification overlay.
//   npx tsx scripts/derive-navgrid-from-nav.ts
import { readFileSync, writeFileSync } from "node:fs";
import { parseNavAreas } from "./parse-nav";

const NAV = "/Users/matthewli/mirage/de_mirage/maps/de_mirage_custom.nav";
const RES = 160;
const M = { posX: -3230, posY: 1713, scale: 5, size: 1024 };
const toR = (x: number, y: number) => ({ x: ((x - M.posX) / M.scale / M.size) * 100, y: ((M.posY - y) / M.scale / M.size) * 100 });

const { areas } = parseNavAreas(NAV);
// radar-space rectangles
const rects = areas.map((a) => {
  const p0 = toR(a.nwX, a.nwY), p1 = toR(a.seX, a.seY);
  return { x0: Math.min(p0.x, p1.x), x1: Math.max(p0.x, p1.x), y0: Math.min(p0.y, p1.y), y1: Math.max(p0.y, p1.y) };
});

const walk = new Uint8Array(RES * RES);
const cell = 100 / RES;
for (const r of rects) {
  const gx0 = Math.max(0, Math.floor(r.x0 / cell)), gx1 = Math.min(RES - 1, Math.floor(r.x1 / cell));
  const gy0 = Math.max(0, Math.floor(r.y0 / cell)), gy1 = Math.min(RES - 1, Math.floor(r.y1 / cell));
  for (let gy = gy0; gy <= gy1; gy += 1) for (let gx = gx0; gx <= gx1; gx += 1) {
    const cx = (gx + 0.5) * cell, cy = (gy + 0.5) * cell; // cell centre must be inside the area
    if (cx >= r.x0 && cx <= r.x1 && cy >= r.y0 && cy <= r.y1) walk[gy * RES + gx] = 1;
  }
}

// keep only the component reachable from T spawn (drops stray out-of-play cells)
const idx = (gx: number, gy: number) => gy * RES + gx;
const start = (() => { const s = toR(1250, -250); return idx(Math.round(s.x / cell), Math.round(s.y / cell)); })();
const tspawnCell = idx(Math.round((86.5 / cell)), Math.round((36.6 / cell)));
const seed = walk[tspawnCell] ? tspawnCell : start;
const keep = new Uint8Array(RES * RES);
const q = [seed]; keep[seed] = 1;
while (q.length) {
  const c = q.pop()!; const gx = c % RES, gy = (c / RES) | 0;
  for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]] as const) {
    const nx = gx + dx, ny = gy + dy;
    if (nx < 0 || ny < 0 || nx >= RES || ny >= RES) continue;
    const ni = idx(nx, ny);
    if (walk[ni] && !keep[ni]) { keep[ni] = 1; q.push(ni); }
  }
}
const walkCount = keep.reduce((s, v) => s + v, 0);

// Both MOVE and VISION use the precise walkable mesh (walls solid). We do NOT dilate vision: the
// apartments wood-door gap is narrow, and dilating it would let players see/shoot through the closed
// door again — the exact bug being fixed. Realistic walls win over a small pacing gain.
const visWalk = keep;
const pack = (mask: Uint8Array, blockedWhenZero: Uint8Array) => {
  const bytes = new Uint8Array(Math.ceil((RES * RES) / 8));
  for (let i = 0; i < RES * RES; i += 1) if (!blockedWhenZero[i]) bytes[i >> 3] |= 1 << (7 - (i & 7));
  return Buffer.from(bytes).toString("base64");
};
const move = pack(keep, keep);
const vision = pack(visWalk, visWalk);
console.log(`RES ${RES}: move ${walkCount} walkable, vision ${visWalk.reduce((s, v) => s + v, 0)} walkable`);

const file = `// AUTO-GENERATED by scripts/derive-navgrid-from-nav.ts — do not edit by hand.
// mirage: derived from the real de_mirage .nav walkable mesh. \`move\` is the precise walkable floor
// (solid walls); \`vision\` is that dilated 1 cell so thin see-over gaps don't block LOS but solid
// walls (e.g. the apartments door) do. Other maps use radar-PNG derivation (scripts/derive-navgrid.ts).
import type { MapId } from "./gameData";

export const navGrids: Partial<Record<MapId, { res: number; move: string; vision: string }>> = {
  mirage: ${JSON.stringify({ res: RES, move, vision })},
};
`;
writeFileSync("src/navGrids.ts", file);
console.log("wrote src/navGrids.ts");

// verification overlay: blocked cells (red) over the radar
const S = 7;
const b64png = readFileSync("src/assets/radar/mirage.png").toString("base64");
const cw = cell * S;
const cells: string[] = [];
for (let gy = 0; gy < RES; gy += 1) for (let gx = 0; gx < RES; gx += 1) if (!keep[gy * RES + gx])
  cells.push(`<rect x="${(gx * cell * S).toFixed(1)}" y="${(gy * cell * S).toFixed(1)}" width="${cw.toFixed(2)}" height="${cw.toFixed(2)}" fill="#ff3b3b" fill-opacity="0.4"/>`);
writeFileSync("scratch/navgrid-blocked.svg", `<svg xmlns="http://www.w3.org/2000/svg" width="${100 * S}" height="${100 * S}" viewBox="0 0 ${100 * S} ${100 * S}"><image href="data:image/png;base64,${b64png}" width="${100 * S}" height="${100 * S}"/>${cells.join("")}</svg>`);
console.log("wrote scratch/navgrid-blocked.svg (red = blocked)");
