import { writeFileSync } from "node:fs";

import { parseNavAreas } from "./parse-nav";

const navPath = process.argv[2] ?? process.env.MIRAGE_NAV_PATH;
if (!navPath) {
  throw new Error("Pass a Mirage .nav path or set MIRAGE_NAV_PATH (npm run generate:mirage-nav -- /path/to/de_mirage.nav).");
}
const outputPath = process.argv[3] ?? "src/mirageNavMesh.ts";
const overview = { posX: -3230, posY: 1713, scale: 5, size: 1024 };

const parsed = parseNavAreas(navPath);
const knownIds = new Set(parsed.areas.map((area) => area.id));
const toRadar = (x: number, y: number) => ({
  x: ((x - overview.posX) / overview.scale / overview.size) * 100,
  y: ((overview.posY - y) / overview.scale / overview.size) * 100,
});
const compactNumber = (value: number, precision = 3) => Number(value.toFixed(precision));

const areas = parsed.areas.map((area) => {
  const nw = toRadar(area.nwX, area.nwY);
  const se = toRadar(area.seX, area.seY);
  const links = [...new Set([...area.connections.flat(), ...area.ladderConnections.flat()])]
    .filter((id) => knownIds.has(id));
  return {
    id: area.id,
    place: area.place,
    bounds: [
      compactNumber(Math.min(nw.x, se.x)),
      compactNumber(Math.min(nw.y, se.y)),
      compactNumber(Math.max(nw.x, se.x)),
      compactNumber(Math.max(nw.y, se.y)),
    ],
    z: compactNumber(area.z, 1),
    attributes: area.attributeFlags,
    links,
    hidingSpots: area.hidingSpots.map((spot) => {
      const point = toRadar(spot.x, spot.y);
      return [compactNumber(point.x), compactNumber(point.y), compactNumber(spot.z, 1), spot.flags];
    }),
    earliestOccupy: area.earliestOccupy.map((time) => compactNumber(time, 2)),
  };
});

const areaData = areas.map((area) => [
  area.id,
  area.place,
  ...area.bounds,
  area.z,
  area.attributes,
  area.links,
  area.hidingSpots,
  area.earliestOccupy,
]);

const source = `// AUTO-GENERATED by scripts/generate-mirage-nav-mesh.ts. Do not edit by hand.
// Source: Valve NAV v${parsed.version}; ${areas.length} connected areas and ${parsed.places.length - 1} named places.

export interface MirageNavArea {
  id: number;
  place: number;
  bounds: [number, number, number, number];
  z: number;
  attributes: number;
  links: number[];
  hidingSpots: Array<[number, number, number, number]>;
  earliestOccupy: [number, number];
}

export const mirageNavPlaces = ${JSON.stringify(parsed.places)} as const;

type MirageNavAreaData = [
  id: number,
  place: number,
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  z: number,
  attributes: number,
  links: number[],
  hidingSpots: Array<[number, number, number, number]>,
  earliestOccupy: [number, number],
];

const mirageNavAreaData: MirageNavAreaData[] = ${JSON.stringify(areaData)};

export const mirageNavAreas: MirageNavArea[] = mirageNavAreaData.map(([
  id,
  place,
  x0,
  y0,
  x1,
  y1,
  z,
  attributes,
  links,
  hidingSpots,
  earliestOccupy,
]) => ({ id, place, bounds: [x0, y0, x1, y1], z, attributes, links, hidingSpots, earliestOccupy }));
`;

writeFileSync(outputPath, source);
console.log(`wrote ${outputPath}: ${areas.length} areas, ${parsed.places.length - 1} places`);
