import type { HltvPlayerSeed, HltvTeamSeed } from "./hltvTop20";
import { makeHltvCoach, makeHltvRoster } from "./hltvTop20";

// Teams that were missing from the built-in database. Starters, ranks, and current-team-period
// samples come from the July 20, 2026 HLTV ranking and the live team roster tables on July 23.
function player(
  handle: string,
  realName: string,
  country: string,
  role: HltvPlayerSeed["role"],
  style: HltvPlayerSeed["style"],
  hltvRating: number,
  maps: number,
  fragSupport = false,
  options: Pick<HltvPlayerSeed, "age" | "playoffNerves" | "statOverrides" | "traits"> = {},
): HltvPlayerSeed {
  return {
    handle,
    realName,
    country,
    role,
    style,
    hltvRating,
    fragSupport: fragSupport || undefined,
    samples: { overall: { rating: hltvRating, maps } },
    ...options,
  };
}

function playoffNerves(baselineAge: number): NonNullable<HltvPlayerSeed["playoffNerves"]> {
  return {
    initialPenalty: 0.08,
    baselineAge,
    fadePerYear: 0.02,
  };
}

export const hltvRosterAdditionSeeds: HltvTeamSeed[] = [
  {
    id: "9z",
    rosterId: "hltv-9z-2026-07-20",
    rankingLabel: "HLTV #6 on July 20, 2026",
    rank: 6,
    points: 370,
    tag: "9Z",
    name: "9z",
    country: "SAM",
    accent: "#8f49d6",
    logoKey: "9z",
    coachHandle: "BIT",
    coachRealName: "Bruno Fukuda Lima",
    coachCountry: "BR",
    coachStyle: "Tactical",
    coachMaps: 260,
    coachTrophies: 0,
    coachWinrate: 57,
    mapBias: { dust2: 2, inferno: 1, nuke: 1 },
    players: [
      // 2026 HLTV filter: max 0.96, luchov 1.19, dgt 1.16, HUASOPEEK 1.13, meyern 1.01.
      // Manual attributes keep the #6 team competitive without turning every good team result into
      // an elite individual card. meyern's 91/100 sniping profile makes him the AWP; luchov's zero
      // sniping usage and high utility/trading output place him in Support.
      player("max", "Maximiliano Gonzalez", "UY", "IGL", "Balanced", 0.96, 179, false, {
        age: 27,
        traits: ["Playoff nerves"],
        playoffNerves: playoffNerves(27),
        statOverrides: { aim: 63, clutch: 67, consistency: 72, awp: 45, igl: 79 },
      }),
      player("luchov", "Luciano Herrera", "AR", "Support", "Balanced", 1.19, 182, false, {
        age: 25,
        traits: ["Playoff nerves"],
        playoffNerves: playoffNerves(25),
        statOverrides: { aim: 87, clutch: 84, consistency: 89, awp: 48, igl: 60 },
      }),
      player("HUASOPEEK", "Matias Ibañez Hernandez", "CL", "Entry", "Aggressive", 1.13, 182, false, {
        age: 23,
        traits: ["Playoff nerves"],
        playoffNerves: playoffNerves(23),
        statOverrides: { aim: 85, clutch: 73, consistency: 74, awp: 48, igl: 50 },
      }),
      player("dgt", "Franco Garcia", "UY", "Lurker", "Balanced", 1.16, 182, false, {
        age: 25,
        traits: ["Playoff nerves"],
        playoffNerves: playoffNerves(25),
        statOverrides: { aim: 89, clutch: 89, consistency: 88, awp: 55, igl: 56 },
      }),
      player("meyern", "Ignacio Meyer", "AR", "AWP", "Passive", 1.01, 182, false, {
        age: 23,
        traits: ["Playoff nerves"],
        playoffNerves: playoffNerves(23),
        statOverrides: { aim: 68, clutch: 70, consistency: 70, awp: 76, igl: 50 },
      }),
    ],
  },
  {
    id: "tyloo",
    rosterId: "hltv-tyloo-2026-07-20",
    rankingLabel: "HLTV #19 on July 20, 2026",
    rank: 19,
    points: 134,
    tag: "TYL",
    name: "TYLOO",
    country: "CN",
    accent: "#d73535",
    logoKey: "tyloo",
    coachHandle: "zhokiNg",
    coachRealName: "WeiJie Zhong",
    coachCountry: "CN",
    coachStyle: "Aggressive",
    coachMaps: 310,
    coachTrophies: 0,
    coachWinrate: 58,
    mapBias: { dust2: 2, mirage: 2, inferno: 1 },
    players: [
      player("Zero", "Su Jingshen", "CN", "IGL", "Balanced", 1.09, 111),
      player("Jee", "Dongkai Ji", "CN", "AWP", "Passive", 1.11, 320),
      player("Mercury", "Jingxiang Wang", "CN", "Entry", "Aggressive", 1.08, 437),
      player("JamYoung", "Yi Yang", "CN", "Lurker", "Balanced", 1.19, 437),
      player("Moseyuh", "Qianhao Chen", "CN", "Support", "Aggressive", 1.11, 366, true),
    ],
  },
  {
    id: "big",
    rosterId: "hltv-big-2026-07-20",
    rankingLabel: "HLTV #21 on July 20, 2026",
    rank: 21,
    points: 112,
    tag: "BIG",
    name: "BIG",
    country: "DE",
    accent: "#e9e9e9",
    logoKey: "big",
    coachHandle: "xenn",
    coachRealName: "Sebastian Hoch",
    coachCountry: "DE",
    coachStyle: "Discipline",
    coachMaps: 128,
    coachTrophies: 0,
    coachWinrate: 52,
    mapBias: { dust2: 2, nuke: 1, train: 1 },
    players: [
      player("tabseN", "Johannes Wodarz", "DE", "IGL", "Aggressive", 1.0, 2110),
      player("gr1ks", "Gleb Gazin", "BY", "AWP", "Passive", 1.14, 154),
      player("JDC", "Jon de Castro", "DE", "Entry", "Aggressive", 1.1, 533),
      player("blameF", "Benjamin Bremer", "DK", "Lurker", "Passive", 1.23, 129),
      player("faveN", "Josef Baumann", "DE", "Support", "Balanced", 1.04, 123, true),
    ],
  },
  {
    id: "luminosity",
    rosterId: "hltv-luminosity-2026-07-20",
    rankingLabel: "HLTV #22 on July 20, 2026",
    rank: 22,
    points: 111,
    tag: "LG",
    name: "Luminosity",
    country: "EU",
    accent: "#3db8e3",
    logoKey: "luminosity-current",
    coachHandle: "—",
    coachRealName: "No listed coach",
    coachCountry: "EU",
    coachStyle: "Discipline",
    coachMaps: 0,
    coachTrophies: 0,
    coachWinrate: 50,
    mapBias: { mirage: 2, ancient: 1, dust2: 1 },
    players: [
      player("lux", "Lucas Meneghini", "BR", "IGL", "Aggressive", 1.14, 5),
      player("afro", "Aurélien Drapier", "FR", "AWP", "Passive", 0.92, 5),
      player("AZUWU", "Oscar Bell", "UK", "Entry", "Aggressive", 0.83, 5),
      player("Bymas", "Aurimas Pipiras", "LT", "Lurker", "Balanced", 0.85, 5),
      player("Rainwaker", "Aleks Petrov", "BG", "Support", "Balanced", 0.97, 5, true),
    ],
  },
  {
    id: "alliance",
    rosterId: "hltv-alliance-2026-07-20",
    rankingLabel: "HLTV #25 on July 20, 2026",
    rank: 25,
    points: 96,
    tag: "ALL",
    name: "Alliance",
    country: "SE",
    accent: "#f0c949",
    logoKey: "alliance",
    coachHandle: "Hawk",
    coachRealName: "Simon Vävinggren",
    coachCountry: "SE",
    coachStyle: "Discipline",
    coachMaps: 156,
    coachTrophies: 0,
    coachWinrate: 54,
    mapBias: { ancient: 2, nuke: 1, inferno: 1 },
    players: [
      player("twist", "Simon Eliasson", "SE", "IGL", "Balanced", 1.0, 801),
      player("eraa", "Sean Knutsson", "SE", "AWP", "Passive", 1.14, 499),
      player("avid", "Arvid Åberg", "SE", "Entry", "Aggressive", 1.0, 810),
      player("bobeksde", "Jonatan Persson", "SE", "Rifler", "Aggressive", 1.11, 33),
      player("upE", "Markus Johansson", "SE", "Support", "Balanced", 0.96, 612),
    ],
  },
  {
    id: "m80",
    rosterId: "hltv-m80-2026-07-20",
    rankingLabel: "HLTV #26 on July 20, 2026",
    rank: 26,
    points: 93,
    tag: "M80",
    name: "M80",
    country: "US",
    accent: "#f0c823",
    logoKey: "m80",
    coachHandle: "dephh",
    coachRealName: "Rory Jackson",
    coachCountry: "UK",
    coachStyle: "Tactical",
    coachMaps: 172,
    coachTrophies: 0,
    coachWinrate: 57,
    mapBias: { inferno: 2, mirage: 1, nuke: 1 },
    players: [
      player("s1n", "Elias Stein", "DE", "IGL", "Balanced", 1.05, 466),
      player("slaxz-", "Fritz Dietrich", "DE", "AWP", "Passive", 1.14, 541),
      player("Lake", "Mason Sanderson", "US", "Entry", "Aggressive", 1.15, 393),
      player("Swisher", "Michael Schmid", "US", "Lurker", "Balanced", 1.0, 610),
      player("JBa", "Josh Barutt", "US", "Support", "Balanced", 1.06, 120, true),
    ],
  },
  {
    id: "k27",
    rosterId: "hltv-k27-2026-07-20",
    rankingLabel: "HLTV #38 on July 20, 2026",
    rank: 38,
    points: 44,
    tag: "K27",
    name: "K27",
    country: "RU",
    accent: "#eb6d4e",
    logoKey: "k27",
    coachHandle: "balblna",
    coachRealName: "Gregory Oleinick",
    coachCountry: "RU",
    coachStyle: "Tactical",
    coachMaps: 118,
    coachTrophies: 0,
    coachWinrate: 55,
    mapBias: { mirage: 2, dust2: 1, ancient: 1 },
    players: [
      player("clax", "Timur Sabirov", "RU", "IGL", "Balanced", 1.07, 5),
      player("qw1nk1", "Daniil Kabilov", "RU", "AWP", "Passive", 1.09, 388),
      player("kashl1d", "Danila Dronov", "RU", "Entry", "Aggressive", 1.12, 428),
      player("xeedo", "Aleksey Mikulich", "BY", "Lurker", "Balanced", 1.12, 430),
      player("X5G7V", "Daniil Maryshev", "RU", "Support", "Balanced", 1.02, 368, true),
    ],
  },
  {
    id: "thunder-downunder",
    rosterId: "hltv-thunder-downunder-2026-07-20",
    rankingLabel: "HLTV #46 on July 20, 2026",
    rank: 46,
    points: 23,
    tag: "TDU",
    name: "THUNDER dOWNUNDER",
    country: "AU",
    accent: "#5cb6dd",
    logoKey: "thunder-downunder",
    coachHandle: "viridian",
    coachRealName: "Eddie Azzi",
    coachCountry: "AU",
    coachStyle: "Aggressive",
    coachMaps: 128,
    coachTrophies: 0,
    coachWinrate: 61,
    mapBias: { nuke: 2, inferno: 1, dust2: 1 },
    players: [
      player("dexter", "Christopher Nong", "AU", "IGL", "Aggressive", 1.04, 128),
      player("aliStair", "Alistair Johnston", "AU", "AWP", "Passive", 1.18, 128),
      player("asap", "Tyson Paterson", "AU", "Entry", "Aggressive", 1.22, 128),
      player("Liazz", "Jay Tregillgas", "AU", "Lurker", "Balanced", 1.21, 128),
      player("TjP", "Tynan Purtell", "AU", "Support", "Balanced", 1.03, 128, true),
    ],
  },
  {
    id: "imperial",
    rosterId: "hltv-imperial-2026-07-20",
    rankingLabel: "HLTV #47 on July 20, 2026",
    rank: 47,
    points: 23,
    tag: "IMP",
    name: "Imperial",
    country: "BR",
    accent: "#54bc70",
    logoKey: "imperial",
    coachHandle: "—",
    coachRealName: "No listed coach",
    coachCountry: "BR",
    coachStyle: "Discipline",
    coachMaps: 0,
    coachTrophies: 0,
    coachWinrate: 50,
    mapBias: { inferno: 2, dust2: 1, ancient: 1 },
    players: [
      player("VINI", "Vinicius Figueiredo", "BR", "IGL", "Balanced", 1.0, 901),
      player("saadzin", "Guilherme Pacheco", "BR", "AWP", "Passive", 1.15, 22),
      player("chelo", "Marcelo Cespedes", "BR", "Entry", "Aggressive", 1.05, 274),
      player("noway", "Kaiky Santos", "BR", "Lurker", "Balanced", 1.08, 694),
      player("decenty", "Lucas Bacelar", "BR", "Support", "Balanced", 1.14, 112, true),
    ],
  },
  {
    id: "fluxo",
    rosterId: "hltv-fluxo-2026-07-20",
    rankingLabel: "HLTV #50 on July 20, 2026",
    rank: 50,
    points: 21,
    tag: "FLX",
    name: "Fluxo",
    country: "BR",
    accent: "#9b74d6",
    logoKey: "fluxo",
    coachHandle: "Juve",
    coachRealName: "Gustavo Alexandre",
    coachCountry: "BR",
    coachStyle: "Tactical",
    coachMaps: 114,
    coachTrophies: 0,
    coachWinrate: 53,
    mapBias: { ancient: 2, mirage: 1, anubis: 1 },
    players: [
      player("exit", "Raphael Lacerda", "BR", "IGL", "Balanced", 1.07, 114),
      player("zevy", "Romeu Rocco", "BR", "AWP", "Passive", 1.0, 641),
      player("kye", "Kayke Bertolucci", "BR", "Entry", "Aggressive", 1.06, 406),
      player("dav1deuS", "David Tapia Maldonado", "CL", "Lurker", "Balanced", 1.09, 37),
      player("Ltz", "João Bonetti", "BR", "Support", "Balanced", 1.05, 37, true),
    ],
  },
  {
    id: "100-thieves",
    rosterId: "hltv-100-thieves-2026-07-20",
    rankingLabel: "HLTV #60 on July 20, 2026",
    rank: 60,
    points: 18,
    tag: "100T",
    name: "100 Thieves",
    country: "EU",
    accent: "#d63636",
    logoKey: "100-thieves",
    coachHandle: "gla1ve",
    coachRealName: "Lukas Rossander",
    coachCountry: "DK",
    coachStyle: "Tactical",
    coachMaps: 124,
    coachTrophies: 4,
    coachWinrate: 53,
    mapBias: { nuke: 2, inferno: 1, ancient: 1 },
    players: [
      player("Gizmy", "Jack von Spreckelsen", "UK", "IGL", "Balanced", 0.86, 9),
      player("device", "Nicolai Reedtz", "DK", "AWP", "Passive", 1.14, 124),
      player("rain", "Håvard Nygaard", "NO", "Entry", "Aggressive", 1.01, 124),
      player("poiii", "Alex Nyholm Sundgren", "SE", "Rifler", "Aggressive", 1.15, 124),
      player("sirah", "William Kjærsgaard", "DK", "Support", "Balanced", 1.07, 124, true),
    ],
  },
  {
    id: "bcgame",
    rosterId: "hltv-bcgame-2026-07-20",
    rankingLabel: "HLTV #200 on July 20, 2026",
    rank: 200,
    points: 3,
    tag: "BCG",
    name: "BC.Game",
    country: "EU",
    accent: "#5bd39c",
    logoKey: "bcgame",
    coachHandle: "TaZ",
    coachRealName: "Wiktor Wojtas",
    coachCountry: "PL",
    coachStyle: "Discipline",
    coachMaps: 51,
    coachTrophies: 0,
    coachWinrate: 31,
    mapBias: { dust2: 2, mirage: 1, inferno: 1 },
    players: [
      // BC.Game's low team rank and tiny new-lineup sample otherwise drag these cards far below the
      // players' established level. Keep the displayed HLTV samples intact, but rate the roster on
      // its actual role shape: Senzu is a tier-one star, mzinho a proven anchor, s1mple the elite
      // primary AWP, electronic a declined veteran, and Magisk a developing full-time IGL.
      player("Magisk", "Emil Reif", "DK", "IGL", "Balanced", 1.06, 1300, false, {
        statOverrides: { aim: 72, clutch: 77, consistency: 75, awp: 50, igl: 78 },
      }),
      player("s1mple", "Oleksandr Kostyliev", "UA", "AWP", "Aggressive", 1.18, 132, false, {
        statOverrides: { aim: 85, clutch: 86, consistency: 79, awp: 90, igl: 50 },
      }),
      player("electroNic", "Denis Sharipov", "RU", "Lurker", "Aggressive", 1.06, 79, false, {
        statOverrides: { aim: 72, clutch: 76, consistency: 68, awp: 50, igl: 64 },
      }),
      player("Senzu", "Azbayar Munkhbold", "MN", "Entry", "Aggressive", 1.03, 7, false, {
        statOverrides: { aim: 93, clutch: 86, consistency: 87, awp: 50, igl: 50 },
      }),
      player("mzinho", "Ayush Batbold", "MN", "Support", "Passive", 0.98, 572, false, {
        statOverrides: { aim: 79, clutch: 80, consistency: 84, awp: 45, igl: 60 },
      }),
    ],
  },
];

export const hltvRosterAdditions = hltvRosterAdditionSeeds.map(makeHltvRoster);
export const hltvRosterAdditionCoaches = hltvRosterAdditionSeeds
  .filter((team) => team.coachHandle !== "—")
  .map(makeHltvCoach);
