import type { HltvPlayerSeed, HltvTeamSeed } from "./hltvTop20";
import { makeHltvCoach, makeHltvRoster } from "./hltvTop20";

// Source snapshot: https://www.hltv.org/ranking/teams/2026/july/13 (ranks 27-50).
// Ratings and sample sizes are the current-team-period values exposed by HLTV on July 13, 2026.
function player(
  handle: string,
  realName: string,
  country: string,
  role: HltvPlayerSeed["role"],
  style: HltvPlayerSeed["style"],
  hltvRating: number,
  maps: number,
  fragSupport = false,
): HltvPlayerSeed {
  return {
    handle,
    realName,
    country,
    role,
    style,
    hltvRating,
    fragSupport: fragSupport || undefined,
    samples: { overall: { rating: hltvRating, maps } },
  };
}

export const hltvRanked27To50Seeds: HltvTeamSeed[] = [
  {
    id: "ninjas-in-pyjamas",
    rosterId: "hltv-ninjas-in-pyjamas-2026-07-13",
    rankingLabel: "HLTV #27 on July 13, 2026",
    rank: 27,
    points: 74,
    tag: "NIP",
    name: "Ninjas in Pyjamas",
    country: "DK",
    accent: "#d8b546",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/mbY2YeFKUAbL9NyO6ab7-c.png?ixlib=java-2.1.0&w=100&s=95466e17ba2af2a72ec28bd1af66ceee",
    coachHandle: "Xizt",
    coachRealName: "Richard Landstrom",
    coachCountry: "SE",
    coachStyle: "Discipline",
    coachMaps: 467,
    coachTrophies: 0,
    coachWinrate: 53,
    mapBias: {"ancient":2,"nuke":1,"mirage":1},
    players: [
      player("Snappi", "Marco Pfeiffer", "DK", "IGL", "Aggressive", 0.93, 336),
      player("stavn", "Martin Lund", "DK", "AWP", "Passive", 1.08, 39),
      player("sjuush", "Rasmus Beck", "DK", "Support", "Passive", 1.11, 336),
      player("n0te", "Roman Hamze", "BE", "Lurker", "Balanced", 1.08, 11),
      player("xKacpersky", "Kacper Gabara", "PL", "Entry", "Aggressive", 1.14, 181),
    ],
  },
  {
    id: "liquid",
    rosterId: "hltv-liquid-2026-07-13",
    rankingLabel: "HLTV #28 on July 13, 2026",
    rank: 28,
    points: 67,
    tag: "LIQ",
    name: "Liquid",
    country: "NAM",
    accent: "#4d76a1",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/JMeLLbWKCIEJrmfPaqOz4O.svg?ixlib=java-2.1.0&s=c02caf90234d3a3ebac074c84ba1ea62",
    coachHandle: "flashie",
    coachRealName: "Viktor Tamas Bea",
    coachCountry: "HU",
    coachStyle: "Tactical",
    coachMaps: 180,
    coachTrophies: 0,
    coachWinrate: 46,
    mapBias: {"inferno":2,"mirage":1,"anubis":1},
    players: [
      player("NAF", "Keith Markovic", "CA", "Lurker", "Passive", 1.14, 1510),
      player("EliGE", "Jonathan Jablonowski", "US", "Entry", "Aggressive", 1.05, 128),
      player("malbsMd", "Mario Samayoa", "GT", "Rifler", "Aggressive", 1.09, 40),
      player("siuhy", "Kamil Szkaradek", "PL", "IGL", "Balanced", 0.88, 210),
      player("Jorko", "Georgi Mitev", "BG", "AWP", "Passive", 1.10, 109),
    ],
  },
  {
    id: "inner-circle",
    rosterId: "hltv-inner-circle-2026-07-13",
    rankingLabel: "HLTV #29 on July 13, 2026",
    rank: 29,
    points: 63,
    tag: "IC",
    name: "Inner Circle",
    country: "UA",
    accent: "#d66b46",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/nzJhoae6HI3i1UORM-DBFD.png?ixlib=java-2.1.0&w=100&s=94c66676b38be4eff71807007b0c4bfe",
    coachHandle: "jR",
    coachRealName: "Dmytro Chervak",
    coachCountry: "UA",
    coachStyle: "Discipline",
    coachMaps: 195,
    coachTrophies: 0,
    coachWinrate: 55,
    mapBias: {"ancient":2,"dust2":1},
    players: [
      player("cptkurtka023", "Arseniy Derevinskiy", "UA", "IGL", "Balanced", 1.05, 138),
      player("headtr1ck", "Daniil Valitov", "UA", "AWP", "Passive", 1.07, 82),
      player("zeRRoFIX", "Eduard Petrovskyi", "UA", "Entry", "Aggressive", 1.02, 138),
      player("onic", "Viktor Babii", "UA", "Support", "Balanced", 0.94, 195),
      player("Dawy", "David Bibik", "UA", "Lurker", "Balanced", 1.15, 195),
    ],
  },
  {
    id: "lynn-vision",
    rosterId: "hltv-lynn-vision-2026-07-13",
    rankingLabel: "HLTV #30 on July 13, 2026",
    rank: 30,
    points: 59,
    tag: "LVG",
    name: "Lynn Vision",
    country: "CN",
    accent: "#d84a45",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/DPcHT21uWwK1hDD_3txlL9.png?ixlib=java-2.1.0&w=100&s=1529ee0026d4e588254fbcd85037eeff",
    coachHandle: "GUM",
    coachRealName: "Yifei Dai",
    coachCountry: "CN",
    coachStyle: "Aggressive",
    coachMaps: 497,
    coachTrophies: 0,
    coachWinrate: 58,
    mapBias: {"dust2":2,"inferno":1},
    players: [
      player("Westmelon", "Zhe Niu", "CN", "IGL", "Balanced", 1.10, 852),
      player("z4KR", "Sike Zhang", "CN", "AWP", "Passive", 1.16, 817),
      player("Starry", "Lizhi Ye", "CN", "Entry", "Aggressive", 1.10, 259),
      player("EmiliaQAQ", "Junjie Tang", "CN", "Support", "Balanced", 1.03, 482),
      player("C4LLM3SU3", "Qihao Su", "CN", "Lurker", "Balanced", 1.00, 230),
    ],
  },
  {
    id: "sharks",
    rosterId: "hltv-sharks-2026-07-13",
    rankingLabel: "HLTV #31 on July 13, 2026",
    rank: 31,
    points: 59,
    tag: "SHK",
    name: "Sharks",
    country: "BR",
    accent: "#4f9ed8",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/xduTwTuydAWc0Dbt-eEjeH.png?ixlib=java-2.1.0&w=100&s=6887f46ff7eedb5f3c040c6782520c68",
    coachHandle: "coachi",
    coachRealName: "Helder Sancho",
    coachCountry: "PT",
    coachStyle: "Aggressive",
    coachMaps: 1619,
    coachTrophies: 0,
    coachWinrate: 58,
    mapBias: {"mirage":2,"anubis":1},
    players: [
      player("gafolo", "Victor Andrade", "BR", "AWP", "Passive", 1.06, 933),
      player("koala", "Joao Pfeffer", "BR", "Support", "Balanced", 1.14, 582),
      player("maxxkor", "Maximo Cortina", "AR", "Entry", "Aggressive", 1.06, 243),
      player("rdnzao", "Daniel Monteiro", "BR", "Lurker", "Balanced", 1.10, 963),
      player("doc", "Danilo Barros", "BR", "IGL", "Balanced", 1.17, 856),
    ],
  },
  {
    id: "nemesis",
    rosterId: "hltv-nemesis-2026-07-13",
    rankingLabel: "HLTV #32 on July 13, 2026",
    rank: 32,
    points: 59,
    tag: "NEM",
    name: "Nemesis",
    country: "RU",
    accent: "#9664d8",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/elLVHPbX3OkW4t8CHjKnoY.png?ixlib=java-2.1.0&w=100&s=4b4e4bd630c54d54d615ffb0c69275ee",
    coachHandle: "NMV",
    coachRealName: "Maksim Naumov",
    coachCountry: "RU",
    coachStyle: "Tactical",
    coachMaps: 203,
    coachTrophies: 0,
    coachWinrate: 61,
    mapBias: {"ancient":2,"nuke":1},
    players: [
      player("SELLTER", "Ivan Miroshnikov", "RU", "IGL", "Balanced", 1.01, 203),
      player("r3salt", "Evgeny Frolov", "RU", "Lurker", "Balanced", 1.15, 137),
      player("mag1k3Y", "Alemkhan Moldakamalov", "KZ", "AWP", "Passive", 1.05, 203),
      player("tex1y", "Philipp Moskvitin", "RU", "Entry", "Aggressive", 1.06, 203),
      player("Sdaim", "Daniil Tupov", "RU", "Support", "Balanced", 1.11, 203, true),
    ],
  },
  {
    id: "3dmax",
    rosterId: "hltv-3dmax-2026-07-13",
    rankingLabel: "HLTV #33 on July 13, 2026",
    rank: 33,
    points: 53,
    tag: "3DM",
    name: "3DMAX",
    country: "FR",
    accent: "#e2a12b",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/QGPDS3Z2-aMXwCYVgA4RWH.png?ixlib=java-2.1.0&w=100&s=6fdbbfe67b4dd4aecfc2554825d72eea",
    coachHandle: "wasiNk",
    coachRealName: "Damien Dufour",
    coachCountry: "FR",
    coachStyle: "Tactical",
    coachMaps: 85,
    coachTrophies: 0,
    coachWinrate: 48,
    mapBias: {"nuke":2,"ancient":1},
    players: [
      player("Maka", "Bryan Canda", "FR", "AWP", "Balanced", 1.09, 642),
      player("Lucky", "Lucas Chastang", "FR", "Lurker", "Passive", 1.05, 644),
      player("misutaaa", "Kevin Rabier", "FR", "Entry", "Aggressive", 1.07, 85),
      player("Kursy", "Jeremy Gast", "FR", "Rifler", "Balanced", 0.96, 5),
      player("Graviti", "Filip Brankovic", "FR", "IGL", "Balanced", 0.98, 587),
    ],
  },
  {
    id: "flyquest",
    rosterId: "hltv-flyquest-2026-07-13",
    rankingLabel: "HLTV #34 on July 13, 2026",
    rank: 34,
    points: 52,
    tag: "FQ",
    name: "FlyQuest",
    country: "AU",
    accent: "#4fbd72",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/fmqTgF6Ziw0uied7MO3_ri.png?ixlib=java-2.1.0&w=100&s=171deb954176f25d79fcec7dd528f4d1",
    coachHandle: "AZR",
    coachRealName: "Aaron Ward",
    coachCountry: "AU",
    coachStyle: "Tactical",
    coachMaps: 76,
    coachTrophies: 0,
    coachWinrate: 59,
    mapBias: {"inferno":2,"dust2":1},
    note: "HLTV listed a four-player active core; story is the last documented 2026 fifth used to keep the roster playable.",
    players: [
      player("jks", "Justin Savage", "AU", "Lurker", "Passive", 1.13, 111),
      player("INS", "Joshua Potter", "AU", "IGL", "Balanced", 1.08, 289),
      player("Vexite", "Declan Portelli", "AU", "Entry", "Aggressive", 1.08, 289),
      player("nettik", "Corey Browne", "NZ", "Support", "Balanced", 1.05, 149),
      player("story", "Joao Vieira", "PT", "AWP", "Passive", 0.99, 57),
    ],
  },
  {
    id: "eyeballers",
    rosterId: "hltv-eyeballers-2026-07-13",
    rankingLabel: "HLTV #35 on July 13, 2026",
    rank: 35,
    points: 49,
    tag: "EYE",
    name: "EYEBALLERS",
    country: "SE",
    accent: "#ed4d48",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/3-Mfc-yWBTls8MPSEFhma5.png?ixlib=java-2.1.0&w=100&s=6ba2cf9cf95c6e57b0438192e5e334dc",
    coachHandle: "pita",
    coachRealName: "Faruk Pita",
    coachCountry: "BA",
    coachStyle: "Aggressive",
    coachMaps: 425,
    coachTrophies: 0,
    coachWinrate: 54,
    mapBias: {"mirage":2,"inferno":1},
    players: [
      player("JW", "Jesper Wecksell", "SE", "AWP", "Aggressive", 1.04, 1144),
      player("KRIMZ", "Freddy Johansson", "SE", "Lurker", "Passive", 1.15, 10),
      player("maxster", "Max Jansson", "SE", "Entry", "Aggressive", 1.11, 325),
      player("Ro1f", "Kalle Johansson", "SE", "Support", "Balanced", 1.02, 360),
      player("dex", "Sebastian Samuelsson", "SE", "IGL", "Balanced", 0.98, 504),
    ],
  },
  {
    id: "nrg",
    rosterId: "hltv-nrg-2026-07-13",
    rankingLabel: "HLTV #36 on July 13, 2026",
    rank: 36,
    points: 43,
    tag: "NRG",
    name: "NRG",
    country: "US",
    accent: "#f26b33",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/SJZaPBCyZssru-pUDS3aZe.png?ixlib=java-2.1.0&w=100&s=f3e3a6ac422d8be2d7b8ad03786a35ae",
    coachHandle: "daps",
    coachRealName: "Damian Steele",
    coachCountry: "CA",
    coachStyle: "Tactical",
    coachMaps: 489,
    coachTrophies: 0,
    coachWinrate: 64,
    mapBias: {"dust2":2,"nuke":1},
    players: [
      player("nitr0", "Nick Cannella", "US", "IGL", "Balanced", 1.06, 410),
      player("Sonic", "Aran Groesbeek", "ZA", "Support", "Balanced", 1.13, 146, true),
      player("hallzerk", "Hakon Fjrli", "NO", "AWP", "Passive", 1.10, 100),
      player("Grim", "Michael Wince", "US", "Lurker", "Balanced", 1.09, 53),
      player("Jeorge", "Jeorge Endicott", "US", "Entry", "Aggressive", 1.03, 8),
    ],
  },
  {
    id: "wildcard",
    rosterId: "hltv-wildcard-2026-07-13",
    rankingLabel: "HLTV #37 on July 13, 2026",
    rank: 37,
    points: 39,
    tag: "WC",
    name: "Wildcard",
    country: "NAM",
    accent: "#7b58c7",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/G1K6vvihgsmN98BxRF8uJ7.png?ixlib=java-2.1.0&w=100&s=8a716dc4a82634440d194992fbf0657e",
    coachHandle: "splawik",
    coachRealName: "ukasz Jahns",
    coachCountry: "PL",
    coachStyle: "Tactical",
    coachMaps: 30,
    coachTrophies: 0,
    coachWinrate: 77,
    mapBias: {"mirage":2,"ancient":1},
    players: [
      player("nEMANHA", "Nemanja ukic", "RS", "IGL", "Balanced", 1.16, 48),
      player("mhL", "Miosz Knasiak", "PL", "AWP", "Passive", 1.15, 99),
      player("Cxzi", "Danny Strzelczyk", "US", "Support", "Balanced", 1.04, 30),
      player("reck", "Ethan Serrano", "US", "Lurker", "Balanced", 1.06, 99),
      player("HexT", "Jadan Postma", "CA", "Entry", "Aggressive", 1.16, 90),
    ],
  },
  {
    id: "heroic",
    rosterId: "hltv-heroic-2026-07-13",
    rankingLabel: "HLTV #38 on July 13, 2026",
    rank: 38,
    points: 37,
    tag: "HER",
    name: "HEROIC",
    country: "SE",
    accent: "#d94a45",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/4S22uk_gnZTiQiI-hhH4yp.png?ixlib=java-2.1.0&w=100&s=a5d9fdc008d14ed3b126835304871d49",
    coachHandle: "doto",
    coachRealName: "Joonas Forss",
    coachCountry: "FI",
    coachStyle: "Tactical",
    coachMaps: 0,
    coachTrophies: 0,
    coachWinrate: 50,
    mapBias: {"nuke":2,"ancient":1},
    players: [
      player("Brollan", "Ludvig Brolin", "SE", "Entry", "Aggressive", 0.98, 80),
      player("nilo", "Linus Bergman", "SE", "Lurker", "Balanced", 1.10, 181),
      player("susp", "Tim Angstrom", "SE", "Support", "Balanced", 1.00, 97),
      player("MartinezSa", "Antonio Martinez", "ES", "AWP", "Passive", 1.16, 197),
      player("Chr1zN", "Christoffer Storgaard", "DK", "IGL", "Balanced", 0.95, 97),
    ],
  },
  {
    id: "acend",
    rosterId: "hltv-acend-2026-07-13",
    rankingLabel: "HLTV #39 on July 13, 2026",
    rank: 39,
    points: 34,
    tag: "ACE",
    name: "Acend",
    country: "BG",
    accent: "#b85be0",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/TslndPhDvsn1bLMdm1j2i6.png?ixlib=java-2.1.0&w=100&s=59913cb4781074edfb7628a074afea79",
    coachHandle: "milky",
    coachRealName: "Milen Iliev",
    coachCountry: "BG",
    coachStyle: "Discipline",
    coachMaps: 100,
    coachTrophies: 0,
    coachWinrate: 51,
    mapBias: {"dust2":2,"mirage":1},
    players: [
      player("SPELLAN", "Teodor Nikolov", "BG", "IGL", "Balanced", 0.93, 218),
      player("REDSTAR", "Hristiyan Pironkov", "BG", "Entry", "Aggressive", 1.12, 68),
      player("KalubeR", "Kalin Erenditsov", "BG", "Lurker", "Balanced", 1.08, 218),
      player("h4rn", "Deyvid Benchev", "BG", "AWP", "Passive", 1.17, 92),
      player("Skrimo", "Dimitar Yanulov", "BG", "Support", "Balanced", 1.04, 218),
    ],
  },
  {
    id: "gentle-mates",
    rosterId: "hltv-gentle-mates-2026-07-13",
    rankingLabel: "HLTV #40 on July 13, 2026",
    rank: 40,
    points: 33,
    tag: "GM",
    name: "Gentle Mates",
    country: "ES",
    accent: "#e66886",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/4vM_jGA-gAmOO3D19rxR1F.png?ixlib=java-2.1.0&w=100&s=9ab0dc51d153799680dca865036579c6",
    coachHandle: "repk3ys",
    coachRealName: "Angel Gracia Navarro",
    coachCountry: "ES",
    coachStyle: "Tactical",
    coachMaps: 53,
    coachTrophies: 0,
    coachWinrate: 60,
    mapBias: {"inferno":2,"nuke":1},
    note: "HLTV listed a four-player active core after MartinezSa moved; the ranking core uses its last documented fifth.",
    players: [
      player("alex", "Alejandro Masanet", "ES", "IGL", "Balanced", 1.02, 197),
      player("mopoz", "Alejandro Fernandez-Quejo Cano", "ES", "Entry", "Aggressive", 1.07, 197),
      player("sausol", "Pere Solsona Saumell", "ES", "Lurker", "Balanced", 1.05, 197),
      player("dav1g", "David Granado Bermudo", "ES", "Support", "Balanced", 1.01, 197),
      player("MartinezSa", "Antonio Martinez", "ES", "AWP", "Passive", 1.16, 197),
    ],
  },
  {
    id: "echo",
    rosterId: "hltv-echo-2026-07-13",
    rankingLabel: "HLTV #41 on July 13, 2026",
    rank: 41,
    points: 32,
    tag: "ECHO",
    name: "Echo",
    country: "DK",
    accent: "#59a9d8",
    coachHandle: "Rejin",
    coachRealName: "Allan Petersen",
    coachCountry: "DK",
    coachStyle: "Discipline",
    coachMaps: 23,
    coachTrophies: 0,
    coachWinrate: 57,
    mapBias: {"ancient":2,"anubis":1},
    players: [
      player("IceBerg", "Oliver Berg", "DK", "IGL", "Balanced", 0.81, 23),
      player("salazar", "Jason Salazar", "DK", "AWP", "Passive", 1.06, 23),
      player("leakz", "Jamie Bugge West Jensen", "DK", "Entry", "Aggressive", 1.27, 23),
      player("Boye", "Jonas Boye stergaard", "DK", "Lurker", "Balanced", 1.00, 23),
      player("NickyB", "Nicky Bruhn", "DK", "Support", "Balanced", 1.07, 23),
    ],
  },
  {
    id: "nuclear-tigeres",
    rosterId: "hltv-nuclear-tigeres-2026-07-13",
    rankingLabel: "HLTV #42 on July 13, 2026",
    rank: 42,
    points: 30,
    tag: "NTR",
    name: "Nuclear TigeRES",
    country: "RU",
    accent: "#e06045",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/_MgIfwkPlbZHTCa-R_s0r-.png?ixlib=java-2.1.0&w=100&s=9adb76cc101840c560c2bfbdd3bb5d22",
    coachHandle: "Polt",
    coachRealName: "Vadim Tsyrov",
    coachCountry: "RU",
    coachStyle: "Aggressive",
    coachMaps: 80,
    coachTrophies: 0,
    coachWinrate: 68,
    mapBias: {"dust2":2,"mirage":1},
    players: [
      player("senka", "Arseniy Kozlovsky", "BY", "IGL", "Balanced", 0.98, 375),
      player("m1QUSE", "Denis Karpovich", "BY", "AWP", "Passive", 1.08, 343),
      player("z1k4", "Timur Askhadulin", "RU", "Lurker", "Balanced", 1.11, 347),
      player("flouzer", "Ilya Selifonov", "RU", "Entry", "Aggressive", 1.13, 375),
      player("ayuki", "Egor Ershov", "RU", "Support", "Balanced", 1.07, 186),
    ],
  },
  {
    id: "hotu",
    rosterId: "hltv-hotu-2026-07-13",
    rankingLabel: "HLTV #43 on July 13, 2026",
    rank: 43,
    points: 29,
    tag: "HOTU",
    name: "HOTU",
    country: "RU",
    accent: "#ec7449",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/P4UciCspVz2jLkse8jAfCN.png?ixlib=java-2.1.0&w=100&s=45705a64c83fe72ce5b19ae0d912b872",
    coachHandle: "mou",
    coachRealName: "Rustem Telepov",
    coachCountry: "KZ",
    coachStyle: "Aggressive",
    coachMaps: 308,
    coachTrophies: 0,
    coachWinrate: 61,
    mapBias: {"mirage":2,"anubis":1},
    players: [
      player("n0rb3r7", "David Danielyan", "RU", "Support", "Balanced", 1.16, 165),
      player("kade0", "Aidos Khairzhan", "KZ", "IGL", "Balanced", 0.95, 38),
      player("mizu", "Dmitry Kondratev", "RU", "Lurker", "Balanced", 1.13, 486),
      player("dwushka", "Aleksandr Pakhnevich", "RU", "Rifler", "Aggressive", 1.13, 12),
      player("frontales", "Kim Argunov", "RU", "Entry", "Aggressive", 1.08, 235),
    ],
  },
  {
    id: "virtus-pro",
    rosterId: "hltv-virtus-pro-2026-07-13",
    rankingLabel: "HLTV #44 on July 13, 2026",
    rank: 44,
    points: 28,
    tag: "VP",
    name: "Virtus.pro",
    country: "RU",
    accent: "#ee6a43",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/yZ6Bpuui1rW3jocXQ68XgZ.svg?ixlib=java-2.1.0&s=f39be1d3e7baf30a4e7f0b1216720875",
    coachHandle: "ProbLeM",
    coachRealName: "Dmitriy Martinov",
    coachCountry: "RU",
    coachStyle: "Discipline",
    coachMaps: 58,
    coachTrophies: 0,
    coachWinrate: 53,
    mapBias: {"ancient":2,"nuke":1},
    players: [
      player("mir", "Nikolay Bityukov", "RU", "IGL", "Balanced", 1.08, 49),
      player("b1st", "Vladimir Krasikov", "RU", "AWP", "Passive", 1.08, 67),
      player("F0R3VER", "Dias Kutubay", "KZ", "Lurker", "Balanced", 0.99, 49),
      player("AquaRS", "Alexander Kovalev", "RU", "Support", "Balanced", 1.03, 48),
      player("tO0RO", "Vadim Arkov", "RU", "Entry", "Aggressive", 0.97, 87),
    ],
  },
  {
    id: "sinners",
    rosterId: "hltv-sinners-2026-07-13",
    rankingLabel: "HLTV #45 on July 13, 2026",
    rank: 45,
    points: 26,
    tag: "SIN",
    name: "SINNERS",
    country: "EU",
    accent: "#d34d45",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/9l_WdQSU9JsNHzpK-pwOG2.svg?ixlib=java-2.1.0&s=af432c3ef61c0c843331cc0dc2fed1ed",
    coachHandle: "Bfull",
    coachRealName: "Jakub Kokoska",
    coachCountry: "CZ",
    coachStyle: "Tactical",
    coachMaps: 474,
    coachTrophies: 0,
    coachWinrate: 56,
    mapBias: {"inferno":2,"nuke":1},
    players: [
      player("beastik", "Sebastian Dano", "CZ", "IGL", "Balanced", 0.99, 1933),
      player("SHOCK", "Max Kvapil", "CZ", "Lurker", "Balanced", 1.06, 1918),
      player("MoDo", "Madalin-Andrei Mirea", "RO", "AWP", "Passive", 1.09, 114),
      player("kisserek", "Kamil Banak", "PL", "Support", "Balanced", 1.09, 286),
      player("stressarN", "Jordan Manevski", "MK", "Entry", "Aggressive", 1.10, 282),
    ],
  },
  {
    id: "fokus",
    rosterId: "hltv-fokus-2026-07-13",
    rankingLabel: "HLTV #46 on July 13, 2026",
    rank: 46,
    points: 24,
    tag: "FOK",
    name: "FOKUS",
    country: "EU",
    accent: "#79d2d0",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/VFmCLfAOw0WUmb_2fDDX3o.png?ixlib=java-2.1.0&w=100&s=3b75ec5687a9e4a656134ddd1011a80c",
    coachHandle: "kuben",
    coachRealName: "Jakub Gurczynski",
    coachCountry: "PL",
    coachStyle: "Tactical",
    coachMaps: 109,
    coachTrophies: 0,
    coachWinrate: 58,
    mapBias: {"nuke":2,"ancient":1},
    note: "HLTV listed a four-player active core after Jorko moved; the ranking core uses its last documented fifth.",
    players: [
      player("ztr", "Erik Gustafsson", "SE", "IGL", "Balanced", 1.01, 109),
      player("volt", "Sebastian Malos", "RO", "Support", "Balanced", 1.01, 109),
      player("Banjo", "Matias Kivisto", "FI", "Lurker", "Passive", 1.12, 109),
      player("Matheos", "Mateo Prislin", "HR", "Entry", "Aggressive", 1.08, 109),
      player("Jorko", "Georgi Mitev", "BG", "AWP", "Passive", 1.10, 109),
    ],
  },
  {
    id: "tdk",
    rosterId: "hltv-tdk-2026-07-13",
    rankingLabel: "HLTV #47 on July 13, 2026",
    rank: 47,
    points: 21,
    tag: "TDK",
    name: "TDK",
    country: "RU",
    accent: "#e15c68",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/6wH8gXfEHnpsR_VufJ2Egb.png?ixlib=java-2.1.0&w=100&s=c47c4eb27556d1ff15dce412da00d6b7",
    coachHandle: "groove",
    coachRealName: "Konstantin Pikiner",
    coachCountry: "RU",
    coachStyle: "Tactical",
    coachMaps: 171,
    coachTrophies: 0,
    coachWinrate: 70,
    mapBias: {"dust2":2,"mirage":1},
    note: "HLTV listed a four-player active core; zorte is the original documented fifth used to keep the roster playable.",
    players: [
      player("Ax1Le", "Sergey Rykhtorov", "RU", "Lurker", "Passive", 1.20, 171),
      player("nafany", "Vladislav Gorshkov", "RU", "IGL", "Aggressive", 1.10, 171),
      player("sugaR", "Amin Azimov", "AZ", "Support", "Balanced", 1.04, 171),
      player("Xant3r", "Kirill Kononov", "RU", "Entry", "Aggressive", 1.06, 171),
      player("zorte", "Aleksandr Zagodyrenko", "RU", "AWP", "Passive", 0.99, 171),
    ],
  },
  {
    id: "walczaki",
    rosterId: "hltv-walczaki-2026-07-13",
    rankingLabel: "HLTV #48 on July 13, 2026",
    rank: 48,
    points: 20,
    tag: "WAL",
    name: "Walczaki",
    country: "PL",
    accent: "#df6b3b",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/7J1EJEnAG7-_sekQrIc_8E.png?invert=true&ixlib=java-2.1.0&sat=-100&w=100&s=578fdf98525257cd7a2a1f8c350131a0",
    coachHandle: "None",
    coachRealName: "None",
    coachCountry: "EU",
    coachStyle: "Discipline",
    coachMaps: 0,
    coachTrophies: 0,
    coachWinrate: 50,
    mapBias: {"mirage":2,"inferno":1},
    players: [
      player("SaMey", "Dawid Stanczak", "PL", "AWP", "Passive", 1.08, 110),
      player("bajmi", "Wojciech Strzelczyk", "PL", "Lurker", "Balanced", 1.04, 110),
      player("sk1tt", "Szymon Rogozinski", "PL", "Support", "Balanced", 1.03, 35),
      player("olimp", "Patryk Wozniak", "PL", "Entry", "Aggressive", 1.12, 110),
      player("moonwalk", "Bartosz Mikoajczyk", "PL", "IGL", "Balanced", 1.07, 110),
    ],
  },
  {
    id: "lp",
    rosterId: "hltv-lp-2026-07-13",
    rankingLabel: "HLTV #49 on July 13, 2026",
    rank: 49,
    points: 20,
    tag: "LP",
    name: "LP",
    country: "BR",
    accent: "#50ad74",
    coachHandle: "disturbed",
    coachRealName: "Pablo Fernandes",
    coachCountry: "BR",
    coachStyle: "Aggressive",
    coachMaps: 108,
    coachTrophies: 0,
    coachWinrate: 59,
    mapBias: {"anubis":2,"mirage":1},
    players: [
      player("zmb", "Leonardo Toledo", "BR", "IGL", "Balanced", 1.12, 108),
      player("Leomonster", "Leonardo Enrique", "BR", "Support", "Balanced", 0.97, 105),
      player("Alisson", "Alisson Farias", "BR", "AWP", "Passive", 1.06, 106),
      player("happ", "Guilherme Bento", "BR", "Lurker", "Balanced", 1.03, 108),
      player("divine", "Gustavo Santicioli Altapini", "BR", "Entry", "Aggressive", 1.05, 96),
    ],
  },
  {
    id: "infinite",
    rosterId: "hltv-infinite-2026-07-13",
    rankingLabel: "HLTV #50 on July 13, 2026",
    rank: 50,
    points: 19,
    tag: "INF",
    name: "INFINITE",
    country: "EU",
    accent: "#7c77d9",
    logoUrl: "https://img-cdn.hltv.org/teamlogo/Bq4oCmwPwqkpV5XvHqmVhI.png?ixlib=java-2.1.0&w=100&s=48b97c34aebfca518a30b4bdaf1edcad",
    coachHandle: "Tionix",
    coachRealName: "Samy von Gehlen",
    coachCountry: "DE",
    coachStyle: "Tactical",
    coachMaps: 90,
    coachTrophies: 0,
    coachWinrate: 50,
    mapBias: {"ancient":2,"dust2":1},
    players: [
      player("kreaz", "Rasmus Johansson", "SE", "Lurker", "Passive", 1.06, 60),
      player("Blytz", "Raul Gligor", "RO", "Entry", "Aggressive", 1.07, 48),
      player("mhN1", "Mihnea Gheata", "RO", "IGL", "Balanced", 0.95, 125),
      player("Dytor", "Martin Handl", "CZ", "Support", "Balanced", 1.06, 58),
      player("sl3nd", "Henrich Hevesi", "HU", "AWP", "Passive", 1.23, 60),
    ],
  },
];

export const hltvRanked27To50Rosters = hltvRanked27To50Seeds.map(makeHltvRoster);
export const hltvRanked27To50Coaches = hltvRanked27To50Seeds
  .filter((team) => team.coachHandle !== "None")
  .map(makeHltvCoach);
